name: big-data
channels:
  - conda-forge
dependencies:
  - bokeh
  - dask
  - dask-jobqueue
  - feather-format
  - findspark
  - jupytext
  - lorem
  - lxml
  - pyarrow
  - pytables
  - python-graphviz
