name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.NBCOURSE_PRIV }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        activate-environment: big-data
        environment-file: environment.yml
    - name: Bash
      shell: bash -l {0}
      run: |
        conda run -n big-data python -m ipykernel install --user --name big-data
        conda run -n base python -m pip install nbcourse
        conda run -n base nbcourse -n 1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: docs
