name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install pandoc
      run: |
        sudo apt-get -yq update
        sudo apt-get install -yq pandoc texlive-xetex texlive-fonts-extra
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.NBCOURSE_PRIV }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Apache Spark
      uses: wei/wget@v1
      with:
        args: https://downloads.apache.org/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
    - name: Install Apache Spark
      run: tar zxf spark-3.0.0-bin-hadoop2.7.tgz
    - uses: Actions-R-Us/default-env@v1
      env:
        SPARK_HOME: '/home/runner/spark-3.0.0-bin-hadoop2.7'
    - name: Install Miniconda and dependencies
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        activate-environment: big-data
        environment-file: environment.yml
    - name: Install nbcourse
      shell: bash -l {0}
      run: |
        conda run -n big-data python -m ipykernel install --user --name big-data
        conda run -n base python -m pip install nbcourse
    - name: Run nbcourse
      shell: bash -l {0}
      run: conda run -n base nbcourse -n 1
    - name: Look for the bug
      shell: bash -l {0}
      run: |
        conda run -n base jupyter nbconvert --to pdf build/01-GitBasics.ipynb
        conda run -n base jupyter nbconvert --to pdf build/02-Installation.ipynb
        conda run -n base jupyter nbconvert --to pdf build/03-JupyterQuickStart.ipynb
        conda run -n base jupyter nbconvert --to pdf build/04-WordCount.ipynb
        conda run -n base jupyter nbconvert --to pdf build/05-MapReduce.ipynb
        conda run -n base jupyter nbconvert --to pdf build/06-ParallelComputation.ipynb
        conda run -n base jupyter nbconvert --to pdf build/07-AsynchronousProcessing.ipynb
        conda run -n base jupyter nbconvert --to pdf build/08-DaskDelayed.ipynb
        conda run -n base jupyter nbconvert --to pdf build/09-DaskBag.ipynb
        conda run -n base jupyter nbconvert --to pdf build/10-PandasSeries.ipynb
        conda run -n base jupyter nbconvert --to pdf build/11-PandaDataframes.ipynb
        conda run -n base jupyter nbconvert --to pdf build/12-PySpark.ipynb
        conda run -n base jupyter nbconvert --to pdf build/13-UnixCommands.ipynb
        conda run -n base jupyter nbconvert --to pdf build/14-Hadoop.ipynb
        conda run -n base jupyter nbconvert --to pdf build/15-HadoopFileFormats.ipynb
        conda run -n base jupyter nbconvert --to pdf build/16-DaskDataframes.ipynb
        conda run -n base jupyter nbconvert --to pdf build/17-SparkDataFrames.ipynb
        conda run -n base jupyter nbconvert --to pdf build/18-NYCTaxiCabTripDask.ipynb
        conda run -n base jupyter nbconvert --to pdf build/19-NYCTaxiCabTripSpark.ipynb
    - name: Deploy on github
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: build
